version: "3.8"

services:
    app:
        image: php:7.4-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - laravel
        depends_on:
            - db

    webserver:
        image: nginx:latest
        container_name: laravel_webserver
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
